#!/bin/sh

#/***************************************************************************
# *   Copyright (C) 2014 deso (deso@posteo.net)                             *
# *                                                                         *
# *   This program is free software: you can redistribute it and/or modify  *
# *   it under the terms of the GNU General Public License as published by  *
# *   the Free Software Foundation, either version 3 of the License, or     *
# *   (at your option) any later version.                                   *
# *                                                                         *
# *   This program is distributed in the hope that it will be useful,       *
# *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
# *   GNU General Public License for more details.                          *
# *                                                                         *
# *   You should have received a copy of the GNU General Public License     *
# *   along with this program.  If not, see <http://www.gnu.org/licenses/>. *
# ***************************************************************************/

# If there are one or more positional arguments then we just pass them to git.
# Otherwise we use the default command which displays the status.
if [ $# -ge 1 ]
then
  COMMAND="git ${@}"
else
  COMMAND="git status --short"
fi

find . -type d -iname ".git" | sed "s!.*!(cd \$(dirname \"\0\") \&\& echo \${PWD} \&\& ${COMMAND})!g" | sh
